### ISSUE TITLE
Unique Client ID

### ISSUE THREAD

**Issue by ankit98verma** [ankit98verma/networkProject#3]
@samvram, At present, Alias is unique in nature and one IP can have multiple Alias. I am gonna change it to one IP one Alias. Also, the IP address of the person changes with time and network so we have to add the entry of mac address. Hence at the end, the story will be <b> one mac one alias </b>
The structure of database will be:
<b> \<mac\> \<alias\> \<ip\> \<status\>  </b>

So everytime client connects to the server, it sends mac id, then server checks it in the database if it does exist then it sends \<alias\> back to the client and set its status in the database to 1 otherwise it sends "not_reg" and you can inform him to set his alias. Then the client can use "alias \<name\>" and the server will check if it is unique or not and things will follow on. Once the alias is assigned then it is preferred to not to change but the user will have the ability to change it anytime and have different but unique \<alias\>. So following are new commands we should add:
<b>alias -rn \<new_alias\> </b>.This is for new alias name.
<b>alias -rm </b>.This will unregister from the server.

**Comment by samvram** [comment]
So while logging in how should the the client send the mac ID to your Server?
