### ISSUE TITLE
Server serving only 1 client

### ISSUE THREAD

**Issue by samvram** [ankit98verma/networkProject#4]
At present, the server only serves one connection. 
We must implement *MultiThreading* to tackle it.
Like every time you accept a connection, create a thread and do something.

As a *temporary* fix for our Beta testers, I have made another server on a different port to communicate on!

Also, I talked to Dr. Manoj.

**Comment by ankit98verma** [comment]
Yeah. I understood what the problem is. I need to make another thread for listening, just like we discussed and did in case of clients. I can do it at night.

**Comment by ankit98verma** [comment]
Server code has been corrected and tested for multiple client access.
